<?php
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
$sum = 2;
$a = 1;
$b = 2;
$next = 3;

while ($next < 4000000) {
    if ($next % 2 == 0) {
        $sum += $next;
    }
    $next = $a + $b;
    $a = $b;
    $b = $next;
}

echo $sum . PHP_EOL;
